=== eegfaktura/eegfaktura-backend/model/ebmsmessage.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/EbmsMessage",
  "$defs": {
    "EbmsMessage": {
      "type": "object",
      "required": [
        "conversationId",
        "sender",
        "receiver",
        "messageCode",
        "messageCodeVersion"
      ],
      "properties": {
        "conversationId": {
          "type": "string"
        },
        "messageId": {
          "type": "string"
        },
        "sender": {
          "type": "string"
        },
        "receiver": {
          "type": "string"
        },
        "messageCode": {
          "type": "string",
          "enum": [
            "DATEN_CRMSG",
            "ANFORDERUNG_ECON",
            "ANTWORT_ECON",
            "ABLEHNUNG_ECON",
            "ZUSTIMMUNG_ECON",
            "ABSCHLUSS_ECON",
            "ABBRUCH_ECON",
            "ANFORDERUNG_ECP",
            "SENDEN_ECP",
            "ABLEHNUNG_ECP",
            "ANFORDERUNG_PT",
            "ANTWORT_PT",
            "ABLEHNUNG_PT",
            "AUFHEBUNG_CCMI",
            "AUFHEBUNG_CCMS",
            "AUFHEBUNG_CCMC",
            "ABLEHNUNG_CCMS",
            "ANTWORT_CCMS",
            "ANFORDERUNG_CPF",
            "ANTWORT_CPF",
            "ABLEHNUNG_CPF",
            "ANFORDERUNG_ECOF",
            "ANTWORT_ECOF",
            "ABLEHNUNG_ECOF",
            "ZUSTIMMUNG_ECOF",
            "ABSCHLUSS_ECOF",
            "ABBRUCH_ECOF",
            "ANFORDERUNG_GN",
            "ERROR_MESSAGE",
            "ERROR_PROCESS"
          ]
        },
        "messageCodeVersion": {
          "type": "string"
        },
        "requestId": {
          "type": "string"
        },
        "meter": {
          "$ref": "#/$defs/Meter"
        },
        "ecId": {
          "type": "string"
        },
        "ecType": {
          "type": "string"
        },
        "ecDisModel": {
          "type": "string"
        },
        "responseData": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ResponseData"
          }
        },
        "energy": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Energy"
          }
        },
        "timeline": {
          "$ref": "#/$defs/Timeline"
        },
        "meterList": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Meter"
          }
        },
        "errorMessage": {
          "type": "string"
        },
        "consentEnd": {
          "type": "integer"
        },
        "reason": {
          "type": "string"
        }
      }
    },
    "Energy": {
      "type": "object",
      "required": [
        "start",
        "end",
        "interval",
        "NInterval",
        "data"
      ],
      "properties": {
        "start": {
          "type": "integer"
        },
        "end": {
          "type": "integer"
        },
        "interval": {
          "type": "string"
        },
        "NInterval": {
          "type": "integer"
        },
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EnergyData"
          }
        }
      }
    },
    "Meter": {
      "type": "object",
      "required": [
        "meteringPoint"
      ],
      "properties": {
        "meteringPoint": {
          "type": "string"
        },
        "direction": {
          "type": "string"
        },
        "activation": {
          "type": "integer"
        },
        "partFact": {
          "type": "integer"
        },
        "from": {
          "type": "integer"
        },
        "to": {
          "type": "integer"
        },
        "plantCategory": {
          "type": "string"
        },
        "share": {
          "type": "number"
        },
        "consentId": {
          "type": "string"
        }
      }
    },
    "ResponseData": {
      "type": "object",
      "required": [
        "meteringPoint",
        "responseCode"
      ],
      "properties": {
        "meteringPoint": {
          "type": "string"
        },
        "responseCode": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "consentEnd": {
          "type": "integer"
        },
        "consentId": {
          "type": "string"
        }
      }
    },
    "Timeline": {
      "type": "object",
      "required": [
        "from",
        "to"
      ],
      "properties": {
        "from": {
          "type": "integer"
        },
        "to": {
          "type": "integer"
        }
      }
    },
    "EnergyValue": {
      "type": "object",
      "required": [
        "from",
        "value"
      ],
      "properties": {
        "from": {
          "type": "integer"
        },
        "to": {
          "type": "integer"
        },
        "method": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      }
    },
    "EnergyData": {
      "type": "object",
      "required": [
        "meterCode",
        "value"
      ],
      "properties": {
        "meterCode": {
          "type": "string"
        },
        "value": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EnergyValue"
          }
        }
      }
    }
  }
}

=== eegfaktura/eegfaktura-backend/tests/ZP_LIST_multi_partfact.json
{
    "conversationId": "RC102271202407171055409960000097389",
    "ecId": "AT00310000000RC102271EGR000320001",
    "messageCode": "SENDEN_ECP",
    "messageCodeVersion": "04.10",
    "messageId": "AT003100202407171055425390111933068",
    "meterList": [
        {
            "activation": 1716760800000,
            "direction": "GENERATION",
            "from": 1716760800000,
            "meteringPoint": "AT0031000000099000000000000017580",
            "partFact": 100,
            "plantCategory": "SONNE",
            "to": 253402210800000
        },
        {
            "activation": 1719525600000,
            "direction": "GENERATION",
            "from": 1719525600000,
            "meteringPoint": "AT0031000000099000000000000018107",
            "partFact": 100,
            "plantCategory": "SONNE",
            "to": 253402210800000
        },
        {
            "activation": 1714600800000,
            "direction": "GENERATION",
            "from": 1714600800000,
            "meteringPoint": "AT0031000000099000000000000018287",
            "partFact": 100,
            "plantCategory": "SONNE",
            "to": 1715983200000
        },
        {
            "activation": 1714600800000,
            "direction": "GENERATION",
            "from": 1716069600000,
            "meteringPoint": "AT0031000000099000000000000018287",
            "partFact": 25,
            "plantCategory": "SONNE",
            "to": 253402210800000
        },
        {
            "activation": 1717365600000,
            "direction": "GENERATION",
            "from": 1717365600000,
            "meteringPoint": "AT0031000000099000000000000018389",
            "partFact": 100,
            "plantCategory": "SONNE",
            "to": 253402210800000
        },
        {
            "activation": 1719439200000,
            "direction": "GENERATION",
            "from": 1719439200000,
            "meteringPoint": "AT0031000000099000000000000018822",
            "partFact": 100,
            "plantCategory": "SONNE",
            "to": 253402210800000
        }
    ],
    "receiver": "RC102271",
    "sender": "AT003100"
}
